Update ip-tracer

diff --git a/modules/ip-tracer b/modules/ip-tracer
--- a/modules/ip-tracer
+++ b/modules/ip-tracer
@@ -2,10 +2,13 @@
 # Author :- Rajkumar Dusad
 # Date :- 10/10/2018
 # Powered By :- Aex Software's
-if [ -d /data/data/com.termux/files/usr/share ];then
-  cd /data/data/com.termux/files/usr/share/IP-Tracer
-  exec bash trace $@
-elif [ -d /usr/share ];then
-  cd /usr/share/IP-Tracer
-  exec bash trace $@
+if [ -d "/data/data/com.termux/files/usr/share/IP-Tracer" ]; then
+  cd "/data/data/com.termux/files/usr/share/IP-Tracer" || exit 1
+  exec bash trace "$@"
+elif [ -d "/usr/share/IP-Tracer" ]; then
+  cd "/usr/share/IP-Tracer" || exit 1
+  exec bash trace "$@"
+else
+  echo "IP-Tracer directory not found."
+  exit 1
 fi
