Update trace

diff --git a/trace b/trace
--- a/trace
+++ b/trace
@@ -1,47 +1,43 @@
 #!/usr/bin/env bash
-# Tool Name :- IP-Tracer
-# Author :- Rajkumar Dusad
-# Date :- 10/10/2018
 
 case "$1" in
   -m)
     php modules/.tracem.php
-  ;;
+    ;;
   -t)
-    case "$#" in
-    2)
-      php modules/.traceip.php $2
+    if [ "$#" -eq 2 ]; then
+      php modules/.traceip.php "$2"
+    else
+      echo "error: invalid arguments!!"
+      echo "usage: trace -t <target_ip>"
+      exit 1
+    fi
     ;;
-    *)
-      echo "error : invalid arguments !!"
-      echo "use: trace -t <target_ip>"
-    ;;
-    esac
-  ;;
-  -u)
+  -u|update)
     php modules/.update.php
     exit
-  ;;
-  update)
-    php modules/.update.php
-    exit
-  ;;
+    ;;
   start)
     php .IP-Tracer.php
     exit
-  ;;
+    ;;
   -rm)
     php modules/.uninstall.php
     exit
-  ;;
+    ;;
+  -h|help)
+    php modules/.help.php
+    exit
+    ;;
   *)
     echo "Usage: trace [command]... [arguments]..."
     echo " Commands:"
     echo " -t <target_ip>      to trace target ip."
     echo " -m                  to trace your own ip."
-    echo " -h                  to show help."
-    echo " -u                  to update ip-tracer."
-    echo " help                to show help."
-    echo " update              to update ip-tracer."
+    echo " -h, help            to show help."
+    echo " -u, update          to update ip-tracer."
     echo " start               to start ip-tracer menu."
+    echo " -rm                 to uninstall ip-tracer."
+    exit 1
+    ;;
 esac
